using System;
using Newtonsoft.Json;

namespace Estuary.Models
{
    /// <summary>
    /// Response model for POST /api/generate/image-to-character.
    /// Maps the camelCase JSON fields returned by agent.to_dict() on the backend.
    /// Only includes fields the app needs - Newtonsoft.Json silently ignores unknown fields.
    /// </summary>
    [Serializable]
    public class AgentResponse
    {
        /// <summary>Agent UUID.</summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>Character name generated by the VLM.</summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>One-liner tagline for the character.</summary>
        [JsonProperty("tagline")]
        public string Tagline { get; set; }

        /// <summary>Personality description (how the character talks and behaves).</summary>
        [JsonProperty("personality")]
        public string Personality { get; set; }

        /// <summary>Character backstory.</summary>
        [JsonProperty("background")]
        public string Background { get; set; }

        /// <summary>Physical description used for 3D model generation.</summary>
        [JsonProperty("appearance")]
        public string Appearance { get; set; }

        /// <summary>Thumbnail image URL.</summary>
        [JsonProperty("avatar")]
        public string Avatar { get; set; }

        /// <summary>Final textured GLB model URL (null until generation completes).</summary>
        [JsonProperty("modelUrl")]
        public string ModelUrl { get; set; }

        /// <summary>Preview GLB model URL (available before texturing completes).</summary>
        [JsonProperty("modelPreviewUrl")]
        public string ModelPreviewUrl { get; set; }

        /// <summary>Current 3D model generation status (generating, preview_ready, completed, failed, texture_failed).</summary>
        [JsonProperty("modelStatus")]
        public string ModelStatus { get; set; }

        public override string ToString()
        {
            return $"AgentResponse(Id={Id}, Name={Name}, ModelStatus={ModelStatus})";
        }
    }
}
